name: Deploy Docs Caller

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: false

jobs:
  call-shared:
    uses: jjainschigg-r/k0rdent-oss-docs/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ github.ref_name }}
